import { useState } from "react";
import { Record, SignedRecord } from "@/lib/types";
import { formatRecordValue } from "@/lib/recordValue";
import RecordForm from "./RecordForm";

interface RecordDetailsProps {
  /** A user record, or a derived DNSSEC row which is shown read-only. */
  record: SignedRecord;
  onRecordChanged: (record: Record) => void;
  defaultEditing?: boolean;
}

export default function RecordDetails({
  record,
  onRecordChanged,
  defaultEditing = false,
}: RecordDetailsProps) {
  const isDerived = record.id == null;
  const [isEditing, setIsEditing] = useState(defaultEditing && !isDerived);

  if (isEditing && !isDerived) {
    return (
      <RecordForm
        // A row with an id is a real user record.
        record={record as Record}
        onSuccess={(updatedRecord) => {
          setIsEditing(false);
          onRecordChanged(updatedRecord);
        }}
        onCancel={() => setIsEditing(false)}
      />
    );
  }

  return (
    <div className="space-y-4">
      <h2 className="flex flex-wrap items-center gap-2 text-2xl font-bold text-gray-800 mb-4">
        <span className="break-all">{record.name}</span>
        <span className="rounded-full bg-gray-100 px-2 py-0.5 text-xs font-medium text-gray-600">
          {record.record_type}
        </span>
        {isDerived && (
          <span className="rounded-full bg-gray-100 px-2 py-0.5 text-xs font-medium text-gray-500">
            Derived
          </span>
        )}
      </h2>

      {isDerived && (
        <p className="text-sm text-gray-500">
          Generated by the signer from the zone&apos;s data and keys; it changes
          with them and cannot be edited.
        </p>
      )}

      <div className="space-y-2">
        <div className="p-2.5 bg-gray-50 rounded-md border border-gray-200">
          <p className="text-sm text-gray-500">Value</p>
          <p
            className={`text-gray-900 break-all ${
              isDerived ? "font-mono text-sm" : "text-base"
            }`}
          >
            {formatRecordValue(record.value)}
          </p>
        </div>
        <div className="grid grid-cols-2 gap-2">
          <div className="p-2.5 bg-gray-50 rounded-md border border-gray-200">
            <p className="text-sm text-gray-500">Type</p>
            <p className="text-base text-gray-900">{record.record_type}</p>
          </div>
          <div className="p-2.5 bg-gray-50 rounded-md border border-gray-200">
            <p className="text-sm text-gray-500">TTL</p>
            <p className="text-base text-gray-900">{record.ttl}</p>
          </div>
          {record.priority != null && (
            <div className="p-2.5 bg-gray-50 rounded-md border border-gray-200">
              <p className="text-sm text-gray-500">Priority</p>
              <p className="text-base text-gray-900">{record.priority}</p>
            </div>
          )}
          <div className="p-2.5 bg-gray-50 rounded-md border border-gray-200">
            <p className="text-sm text-gray-500">Zone</p>
            <p className="text-base text-gray-900">
              {record.zone_name ?? record.zone_id}
            </p>
          </div>
        </div>
      </div>

      {!isDerived && (
        <div className="flex justify-end">
          <button
            type="button"
            onClick={() => setIsEditing(true)}
            className="btn-primary"
          >
            Edit Record
          </button>
        </div>
      )}
    </div>
  );
}
