name: CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: ui/package-lock.json

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: Install frontend dependencies
        working-directory: ./ui
        run: npm ci

      - name: Build frontend
        working-directory: ./ui
        run: npm run build

      - name: Download Go dependencies
        run: go mod download

      - name: Build Go application
        run: go build -o bindizr-ui main.go

      - name: Quick smoke test
        run: |
          timeout 5s ./bindizr-ui || if [ $? -eq 124 ]; then 
            echo "✅ Application starts successfully"
          else 
            echo "❌ Application failed to start"
            exit 1
          fi
